
if test -z "${QMAKE}" ; then
    QMAKE=qmake
fi

## REMEMBER: any changes below should also be applied to
## quilt.pro.win

echo "

## NOTE: autogenerated by createProject.sh -- do not modify!!

TEMPLATE = lib

QT += widgets

# Input

# HEADERS += primitives.h

SOURCES += init.c imports.cpp 
SOURCES += primitives.cpp

INCLUDEPATH += ${R_INCLUDE_DIR}
INCLUDEPATH += ${CLINK_CPPFLAGS/-I/}



macx{
LIBS += -framework R
}
unix{
LIBS += -L${R_HOME}/lib
}
win32{
LIBS += -L${R_HOME}/bin -lR
}

" > quilt.pro

if test `uname` == "Darwin" ; then
    ${QMAKE} -spec macx-g++ -o Makefile.quilt
else 
    ${QMAKE} -o Makefile.quilt
fi

## if macx; do 
##     ${QMAKE} -spec macx-g++ -o Makefile.quilt
## else

